#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsBp4LKIGIpAnrQ1+a4TjUbtbSmLd1R+YEy8x+9OWfv freemos@MOS-PC01